// <auto-generated />
namespace Kitchinv.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20150501727 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20150501727));
        
        string IMigrationMetadata.Id
        {
            get { return "201505011127334_20150501-727"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
